apiVersion: v1
kind: Secret
metadata:
  name: beroo-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://202201677_db_user:uzx8v5u3pP9Nkx4b@e-business-porject\
    -s-cl.ipfdobu.mongodb.net/gymstore?retryWrites=true&w=majority&appName=E-Bu\
    siness-Porject-s-Cluster"
  JWT_SECRET: "gymstore_super_secret_key_2024"
